Create an array a with numbers 0..11 and reshape it to (3, 4).

Print a.shape, a.ndim, and a.dtype.

Extract:

the last row of a;

the first two elements of the second column (as a 1D array).

Create squared = a**2 (vectorized).

In-place, set every value in a that is a multiple of 3 to -1 (use a boolean mask).

Finally, show me both a and squared.

In [38]:
import numpy as np

a = np.arange(12).reshape(3,4)
print(a.shape, a.ndim, a.dtype)

print(a)
print(a[-1, :])
print(a[0:2, 1])
squared = a **2
print(squared)
mask = (a % 3 == 0)
print(mask)
a[mask] = -1
print(a)

(3, 4) 2 int64
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 5]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[ True False False  True]
 [False False  True False]
 [False  True False False]]
[[-1  1  2 -1]
 [ 4  5 -1  7]
 [ 8 -1 10 11]]


Create a = np.arange(1, 31).reshape(5, 6) (values 1..30).

Using slicing, get the middle 3 rows and columns 2–4 (i.e., rows 1:4 and cols 1:4). Print it.

Get every other row of a in reverse column order using one slice. Print it.

Using a boolean mask, set every element of a that’s divisible by 5 to -5 in-place. Print a.

Using fancy indexing, select rows [0, 2, 4] and columns [1, 3, 5] as a rectangular submatrix (hint: np.ix_). Print the result.

In [51]:
a = np.arange(1,31).reshape(5,6)
print(a)
print(a[1:4, 1:4])
print(a[::2,::-1])
mask = (a % 5 ==0)
a[mask] = -5
print(a)
rows, cols = [0,2,4],[1,3,5]
sub = a[np.ix_(rows, cols)]
print(sub)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
[[ 8  9 10]
 [14 15 16]
 [20 21 22]]
[[ 6  5  4  3  2  1]
 [18 17 16 15 14 13]
 [30 29 28 27 26 25]]
[[ 1  2  3  4 -5  6]
 [ 7  8  9 -5 11 12]
 [13 14 -5 16 17 18]
 [19 -5 21 22 23 24]
 [-5 26 27 28 29 -5]]
[[ 2  4  6]
 [14 16 18]
 [26 28 -5]]


b = np.arange(24).reshape(4, 6)

Make c = b.reshape(2, 12) and set c[0, :3] = 99. Then print(b) to observe effects.

Get r = b.ravel() and set the last 4 elements of r to -1. print(b) again.

Make d = b.flatten() and set d[:5] = 777. Print both b and d.

Create:

col = np.arange(1,4).reshape(3,1)

row = np.arange(10,13)
Build and print:

M_h = np.hstack([col, row.reshape(3,1)]) # shape (3,2)

M_v = np.vstack([row, row+100]) # shape (2,3)

M_s = np.stack([row, row+100], axis=1) # shape (3,2)

Use np.concatenate to append two rows of zeros to b (so final shape is (6, 6)). Print the result.

In [80]:
b = np.arange(24).reshape(4,6)
c = b.reshape(2,12)
c[0, :3] =99
print(b)
r = b.ravel()
print(r)
r[-4:] = -1
print(r)
print(b)
d = b.flatten()
d[:5] = 777
print(b)
print(d)

col = np.arange(1,4).reshape(3,1)
row = np.arange(10,13)

print(col)
print(row)

M_h = np.hstack([col, row.reshape(3,1)])
M_v = np.vstack([row, row+100])
print(M_v)

M_s = np.stack([row, row+100], axis =1 )

b = np.concatenate([b, np.zeros(12).reshape(2,6)])
print(b)

[[99 99 99  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[99 99 99  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[99 99 99  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 -1 -1 -1 -1]
[[99 99 99  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 -1 -1 -1 -1]]
[[99 99 99  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 -1 -1 -1 -1]]
[777 777 777 777 777   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  -1  -1  -1  -1]
[[1]
 [2]
 [3]]
[10 11 12]
[[ 10  11  12]
 [110 111 112]]
[[99. 99. 99.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


Create:

A = np.array([[3, 1, 9],
              [2, 8, 5],
              [0, 4, 7]])


Compute col_sums = A.sum(axis=0) and row_means = A.mean(axis=1). Print both.

Find the index of the max in each row: idx = A.argmax(axis=1).

Use np.take_along_axis to get the max values per row. Print the indices and values.

Make a 3D array: X = np.arange(24).reshape(2, 3, 4).

Compute X.argmax() (flat) and convert it to 3D indices with np.unravel_index.

Print the 3D index tuple and the max value at that location.

On the same X, compute last_axis_argmin = X.argmin(axis=2) (shape (2,3)).

Use np.take_along_axis to fetch the corresponding min values along the last axis (shape (2,3)). Print them.

In [ ]:
A = np.array([[3, 1, 9],
              [2, 8, 5],
              [0, 4, 7]])

ind = np.argmax(A, axis=1)
print(ind)
print(A.argmax(axis = 1))
print(np.take_along_axis(A, ind[:, None], axis = 1).ravel())

[2 1 2]
[2 1 2]
[9 8 7]
23


Broadcasting

In [ ]:
A = np.arange(12).reshape(3,4)

col_bias = np.array([10,20,30,40])
A_plus = A + col_bias
print(A_plus)

row_bias = np.array([0,100,200])
A_Plus2 = A + row_bias[:, None]
print(A_Plus2)

# Column-centering
A_centered = A - A.mean(axis=0, keepdims=True)
print(A_centered)

[[10 21 32 43]
 [14 25 36 47]
 [18 29 40 51]]
[[  0   1   2   3]
 [104 105 106 107]
 [208 209 210 211]]
